# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28ab5d0766e138466b92ca1b88785516cfe9fa9d2f079787c5ebeedfa62277e2d8e713af46a284359724762a983d415580ec2a8be11625ff587c14007825379a

test:
  secret_key_base: ee7eb65d69f47c8adb5e719a126b67b988a8ddeb10af0fdd697b1db850a2c8569761bf2b01b0b4ceec603cbefd8fdeb44ce060c083be42dc64d0473ae26873fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
